title: Movies Updater
show_downloads: true
github:
  zip_url: https://github.com/MasterZayaan/movies-updater/raw/main/versions/movies-updater-all-versions.zip
google_analytics:
theme: jekyll-theme-hacker
